// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartElectionCertificationCentre.Data;

namespace SmartElectionCertificationCentre.Migrations
{
    [DbContext(typeof(PrivateContext))]
    [Migration("20190516042311_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartElectionCertificationCentre.Models.PrivateKey", b =>
                {
                    b.Property<string>("CertificateThumbprint")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("D")
                        .IsRequired();

                    b.Property<string>("DP")
                        .IsRequired();

                    b.Property<string>("DQ")
                        .IsRequired();

                    b.Property<string>("Exponent")
                        .IsRequired();

                    b.Property<string>("InverseQ")
                        .IsRequired();

                    b.Property<string>("Modulus")
                        .IsRequired();

                    b.Property<string>("P")
                        .IsRequired();

                    b.Property<string>("Q")
                        .IsRequired();

                    b.HasKey("CertificateThumbprint");

                    b.ToTable("PrivateKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
